service: kiosk-pools-poc
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  api:
    handler: src/handlers/index.handler
    events:
      - httpApi:
          path: /
          method: get
