service: serverless-ts-demo
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${opt:stage, 'dev'}

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  getDummy:
    handler: src/handlers/index.handler
    events:
      - httpApi:
          path: /
          method: get
