name: Run unit tests

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    types: [opened, reopened]
    branches: [development, main]

env:
  development: development
  main: production
  # stage: ${{env[ ${{github.ref_name}} ]}} 

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    # environment: ${{ env[github.ref_name] }}
    steps:
    # - uses: actions/checkout@v3
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: ${{ matrix.node-version }}
    # - run: npm ci
    - name: Run unit tests
      # run: npm run test:unit
      # run: echo Result env mapping is ${{ vars.STAGE }}
      run: echo Env mapping is ${{ github.ref_name }}
