name: Run unit tests

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    types: [opened, reopened]
    branches: [development, main]

env:
  development: development
  main: production
  branch: ${{ github.base_ref || 'development' }}
  stage: ${{ github.base_ref == 'main' && 'production' || 'development' }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    # environment: ${{ env['development'] }}
    steps:
    # - uses: actions/checkout@v3
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: ${{ matrix.node-version }}
    # - run: npm ci
    - name: Run unit tests
      # run: npm run test:unit
      # run: echo Test if env assignation is fine. -> ${{ vars.STAGE }}
      run: echo Test var. ${{ env.stage }} branch name is -> ${{ env.stage }}
