name: Run unit tests

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    types: [opened, reopened]
    branches: [development, main]

env:
  development: dev
  main: prod
  # stage: ${{ env.${{ GITHUB_BASE_REF }} }}

jobs:
  run-tests:
    name: Build and deploy
    runs-on: ubuntu-latest
    environment:
      # name: env.${{ GITHUB_BASE_REF }}
      name: dev
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Run unit tests
      run: npm run test:unit
    - name: Log environment
    - run: echo "Environment"